version: '3.7'
services:
  mongo:
    container_name: mongo-container
    image: mongo:latest
    restart: always
    volumes:
      - mongo_data:/data/db
    ports:
      - "27017:27017"
  app:
    build: .
    container_name: useprod
    restart: always
    command: npm run watch
    volumes:
      - ./src:/usr/src/useprod/src
      - ./package.json:/usr/src/useprod/package.json
      - ./dist:/usr/src/useprod/dist/
    ports: 
      - 8088:8088
      - 9229:9229
    env_file:
      - .env
    depends_on:
      - mongo
volumes:
  mongo_data:
    

