version: "3"
services:
  mongo:
    container_name: mongo-container
    image: mongo:5
    restart: always
    volumes:
      - ./data:/data/db
    ports:
      - "27017:27017"
  api: 
    container_name: api-container
    build: .
    restart: always
    image: usefashionstore
    command: npm start
    volumes:
      - ./dist:/usr/src/usefashionstore/backend/dist
    ports:
      - "8081:8081"
    links:
      - mongo